import json
import os

def update_training_notebook():
    nb_path = 'src/notebooks/training.ipynb'
    with open(nb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # Cell 0: Header
    nb['cells'][0]['source'] = [
        "# CSIRO Image2Biomass: Fast 2-Stage DINOv2-Small Training Pipeline\n",
        "# Integrates 2nd Place Solution: 3 Base Targets, State Stratification, WA Zero-Dead & Multiplier Post-Processing\n"
    ]

    # Cell 2: Configuration
    nb['cells'][2]['source'] = [
        "# 2. Configuration & Automatic Path Discovery\n",
        "import os\n",
        "import sys\n",
        "import random\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "from torch.optim import AdamW\n",
        "from torch.optim.lr_scheduler import CosineAnnealingLR\n",
        "from sklearn.model_selection import StratifiedKFold\n",
        "import timm\n",
        "from tqdm.auto import tqdm\n",
        "\n",
        "class CFG:\n",
        "    SEED = 42\n",
        "    BACKBONE = 'vit_small_patch14_dinov2'\n",
        "    IMG_SIZE = 518\n",
        "    BATCH_SIZE = 16\n",
        "    LR = 3e-4\n",
        "    BACKBONE_LR_FACTOR = 0.1  # 3e-5 for backbone\n",
        "    WEIGHT_DECAY = 0.05\n",
        "    N_FOLDS = 5\n",
        "    STAGE1_EPOCHS = 7   # Heads warm-up (backbone frozen)\n",
        "    STAGE2_EPOCHS = 23  # Full fine-tuning (backbone unfrozen)\n",
        "    FUSION_DIM = 384\n",
        "    DROPOUT = 0.3\n",
        "    USE_TTA = True\n",
        "    BASE_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g']\n",
        "    ALL_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']\n",
        "    OFFICIAL_WEIGHTS = [0.1, 0.1, 0.1, 0.2, 0.5]\n",
        "    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
        "\n",
        "def set_seed(seed=CFG.SEED):\n",
        "    random.seed(seed)\n",
        "    np.random.seed(seed)\n",
        "    torch.manual_seed(seed)\n",
        "    torch.cuda.manual_seed_all(seed)\n",
        "    torch.backends.cudnn.deterministic = True\n",
        "    torch.backends.cudnn.benchmark = False\n",
        "\n",
        "set_seed(CFG.SEED)\n",
        "\n",
        "# Auto-detect Kaggle vs local paths\n",
        "KAGGLE_DIR = '/kaggle/input/csiro-biomass'\n",
        "LOCAL_DIR = '.'\n",
        "DATA_DIR = KAGGLE_DIR if os.path.exists(KAGGLE_DIR) else LOCAL_DIR\n",
        "TRAIN_CSV = os.path.join(DATA_DIR, 'train.csv')\n",
        "TEST_CSV = os.path.join(DATA_DIR, 'test.csv')\n",
        "OUTPUT_DIR = '/kaggle/working' if os.path.exists('/kaggle') else './models'\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "print(f'Running on {CFG.DEVICE} | Backbone: {CFG.BACKBONE} | Data: {DATA_DIR}')\n"
    ]

    # Cell 3: Metrics & 2nd Place Post-Processing
    nb['cells'][3]['source'] = [
        "# 3. Target Derivation, 2nd Place Post-Processing & Competition Metric\n",
        "def derive_5_targets(preds_3):\n",
        "    \"\"\"Derives GDM = Green + Clover and Total = Green + Dead + Clover from 3 base targets.\"\"\"\n",
        "    preds_np = np.asarray(preds_3, dtype=np.float32)\n",
        "    if preds_np.ndim == 1:\n",
        "        preds_np = preds_np.reshape(1, -1)\n",
        "    green = preds_np[:, 0:1]\n",
        "    dead = preds_np[:, 1:2]\n",
        "    clover = preds_np[:, 2:3]\n",
        "    gdm = green + clover\n",
        "    total = green + dead + clover\n",
        "    return np.concatenate([green, dead, clover, gdm, total], axis=-1)\n",
        "\n",
        "def apply_2nd_place_postprocess(preds_5, states=None):\n",
        "    \"\"\"\n",
        "    2nd Place Post-Processing:\n",
        "    1. WA Dead Zeroing: Ground truth in WA has 0.0 dead biomass.\n",
        "    2. State Multiplier Scaling:\n",
        "       - NSW: Green *= 1.03\n",
        "       - Vic: Clover *= 0.85\n",
        "       - WA: Clover *= 0.80, Dead *= 0.80, Green *= 0.97\n",
        "    3. Range Clipping to Training Bounds:\n",
        "       - Clover in [0, 71.7865], Dead in [0, 83.8407], Green in [0, 157.9836]\n",
        "    4. Recompute Physical Identities (GDM and Total).\n",
        "    \"\"\"\n",
        "    preds = np.maximum(np.asarray(preds_5, dtype=np.float32).copy(), 0.0)\n",
        "    if preds.ndim == 1:\n",
        "        preds = preds.reshape(1, -1)\n",
        "    green = preds[:, 0].copy()\n",
        "    dead = preds[:, 1].copy()\n",
        "    clover = preds[:, 2].copy()\n",
        "\n",
        "    if states is not None:\n",
        "        for idx, st in enumerate(states):\n",
        "            st_str = str(st).strip()\n",
        "            if st_str == 'WA':\n",
        "                dead[idx] = 0.0\n",
        "                clover[idx] *= 0.80\n",
        "                green[idx] *= 0.97\n",
        "            elif st_str == 'Vic':\n",
        "                clover[idx] *= 0.85\n",
        "            elif st_str == 'NSW':\n",
        "                green[idx] *= 1.03\n",
        "\n",
        "    clover = np.clip(clover, 0.0, 71.7865)\n",
        "    dead = np.clip(dead, 0.0, 83.8407)\n",
        "    green = np.clip(green, 0.0, 157.9836)\n",
        "\n",
        "    gdm = green + clover\n",
        "    total = green + dead + clover\n",
        "    return np.column_stack([green, dead, clover, gdm, total])\n",
        "\n",
        "def calculate_competition_r2(y_true, y_pred, weights=CFG.OFFICIAL_WEIGHTS):\n",
        "    y_true = np.array(y_true, dtype=float)\n",
        "    y_pred = np.array(y_pred, dtype=float)\n",
        "    w = np.array(weights, dtype=float)\n",
        "    if y_true.ndim == 1: y_true = y_true.reshape(-1, 5)\n",
        "    if y_pred.ndim == 1: y_pred = y_pred.reshape(-1, 5)\n",
        "    yt = np.log1p(np.maximum(0, y_true))\n",
        "    yp = np.log1p(np.maximum(0, y_pred))\n",
        "    r2_scores = []\n",
        "    for i in range(5):\n",
        "        ss_res = np.sum((yt[:, i] - yp[:, i]) ** 2)\n",
        "        ss_tot = np.sum((yt[:, i] - np.mean(yt[:, i])) ** 2)\n",
        "        score = 1.0 - (ss_res / ss_tot) if ss_tot > 0 else (1.0 if ss_res == 0 else 0.0)\n",
        "        r2_scores.append(score)\n",
        "    return float(np.sum(w * np.array(r2_scores)))\n"
    ]

    # Cell 4: Preprocessing & Dataset
    nb['cells'][4]['source'] = [
        "# 4. Dual-Stream Dataset with White Balance & Shadow Correction\n",
        "import cv2\n",
        "from PIL import Image\n",
        "from torchvision import transforms\n",
        "\n",
        "def apply_white_balance_gray_world(image_np):\n",
        "    img = image_np.astype(np.float32)\n",
        "    avg_r = np.mean(img[:, :, 0])\n",
        "    avg_g = np.mean(img[:, :, 1])\n",
        "    avg_b = np.mean(img[:, :, 2])\n",
        "    avg_gray = (avg_r + avg_g + avg_b) / 3.0\n",
        "    if avg_r > 0: img[:, :, 0] = np.clip(img[:, :, 0] * (avg_gray / avg_r), 0, 255)\n",
        "    if avg_g > 0: img[:, :, 1] = np.clip(img[:, :, 1] * (avg_gray / avg_g), 0, 255)\n",
        "    if avg_b > 0: img[:, :, 2] = np.clip(img[:, :, 2] * (avg_gray / avg_b), 0, 255)\n",
        "    return img.astype(np.uint8)\n",
        "\n",
        "def apply_hsv_shadow_correction(image_np, prob=0.4):\n",
        "    if random.random() > prob: return image_np\n",
        "    hsv = cv2.cvtColor(image_np, cv2.COLOR_RGB2HSV)\n",
        "    h, s, v = cv2.split(hsv)\n",
        "    v_mean, v_std = np.mean(v), np.std(v)\n",
        "    shadow_thresh = max(0, v_mean - 0.5 * v_std)\n",
        "    shadow_mask = v < shadow_thresh\n",
        "    if shadow_mask.any():\n",
        "        non_shadow_mean = np.mean(v[~shadow_mask]) if (~shadow_mask).any() else v_mean\n",
        "        shadow_mean = np.mean(v[shadow_mask])\n",
        "        if shadow_mean > 0:\n",
        "            scale = min(non_shadow_mean / shadow_mean, 1.8)\n",
        "            v_corr = v.copy().astype(np.float32)\n",
        "            v_corr[shadow_mask] = np.clip(v_corr[shadow_mask] * scale, 0, 255)\n",
        "            return cv2.cvtColor(cv2.merge([h, s, v_corr.astype(np.uint8)]), cv2.COLOR_HSV2RGB)\n",
        "    return image_np\n",
        "\n",
        "class DualStreamDataset(Dataset):\n",
        "    def __init__(self, df, img_size=518, is_train=True, target_cols=CFG.BASE_TARGETS):\n",
        "        self.df = df.reset_index(drop=True)\n",
        "        self.img_size = img_size\n",
        "        self.is_train = is_train\n",
        "        self.target_cols = target_cols\n",
        "        self.has_targets = all(c in self.df.columns for c in self.target_cols)\n",
        "        if self.has_targets:\n",
        "            self.targets = self.df[self.target_cols].values.astype(np.float32)\n",
        "        \n",
        "        mean = (0.485, 0.456, 0.406)\n",
        "        std = (0.229, 0.224, 0.225)\n",
        "        if is_train:\n",
        "            self.tf = transforms.Compose([\n",
        "                transforms.Resize((img_size, img_size)),\n",
        "                transforms.RandomHorizontalFlip(0.5),\n",
        "                transforms.RandomVerticalFlip(0.5),\n",
        "                transforms.ColorJitter(0.2, 0.2, 0.2, 0.1),\n",
        "                transforms.ToTensor(),\n",
        "                transforms.Normalize(mean, std)\n",
        "            ])\n",
        "        else:\n",
        "            self.tf = transforms.Compose([\n",
        "                transforms.Resize((img_size, img_size)),\n",
        "                transforms.ToTensor(),\n",
        "                transforms.Normalize(mean, std)\n",
        "            ])\n",
        "\n",
        "    def __len__(self):\n",
        "        return len(self.df)\n",
        "\n",
        "    def _resolve_path(self, p):\n",
        "        for prefix in [DATA_DIR, '/kaggle/input/csiro-biomass', '.']:\n",
        "            cand = os.path.join(prefix, p)\n",
        "            if os.path.exists(cand): return cand\n",
        "            fname = os.path.basename(p)\n",
        "            for sub in ['train', 'test']:\n",
        "                cand2 = os.path.join(prefix, sub, fname)\n",
        "                if os.path.exists(cand2): return cand2\n",
        "        return p\n",
        "\n",
        "    def __getitem__(self, idx):\n",
        "        row = self.df.iloc[idx]\n",
        "        p = self._resolve_path(row['image_path'])\n",
        "        bgr = cv2.imread(p)\n",
        "        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)\n",
        "        h, w = rgb.shape[:2]\n",
        "        mid = w // 2\n",
        "        l_np, r_np = rgb[:, :mid].copy(), rgb[:, mid:].copy()\n",
        "        l_np = apply_white_balance_gray_world(l_np)\n",
        "        r_np = apply_white_balance_gray_world(r_np)\n",
        "        if self.is_train:\n",
        "            l_np = apply_hsv_shadow_correction(l_np, 0.4)\n",
        "            r_np = apply_hsv_shadow_correction(r_np, 0.4)\n",
        "            if random.random() < 0.5: l_np, r_np = r_np, l_np\n",
        "        t_l = self.tf(Image.fromarray(l_np))\n",
        "        t_r = self.tf(Image.fromarray(r_np))\n",
        "        item = {'img_l': t_l, 'img_r': t_r, 'sample_id': row.get('sample_id', str(idx))}\n",
        "        if self.has_targets:\n",
        "            item['targets'] = torch.tensor(self.targets[idx], dtype=torch.float32)\n",
        "        return item\n"
    ]

    # Cell 5: Model
    nb['cells'][5]['source'] = [
        "# 5. DualStreamBiomassModel Architecture (DINOv2-Small)\n",
        "class DualStreamBiomassModel(nn.Module):\n",
        "    def __init__(self, backbone_name=CFG.BACKBONE, num_targets=3, fusion_dim=CFG.FUSION_DIM, dropout=CFG.DROPOUT, pretrained=True):\n",
        "        super().__init__()\n",
        "        kwargs = {'dynamic_img_size': True} if ('dinov2' in backbone_name or 'patch14' in backbone_name) else {}\n",
        "        self.backbone = timm.create_model(backbone_name, pretrained=pretrained, num_classes=0, **kwargs)\n",
        "        self.backbone_dim = self.backbone.num_features\n",
        "        num_heads = 8 if self.backbone_dim % 8 == 0 else 4\n",
        "        self.cross_view_attn = nn.MultiheadAttention(self.backbone_dim, num_heads, dropout=0.1, batch_first=True)\n",
        "        self.attn_norm = nn.LayerNorm(self.backbone_dim)\n",
        "        self.fusion_mlp = nn.Sequential(\n",
        "            nn.Linear(self.backbone_dim * 2, fusion_dim),\n",
        "            nn.LayerNorm(fusion_dim),\n",
        "            nn.GELU(),\n",
        "            nn.Dropout(dropout)\n",
        "        )\n",
        "        self.reg_heads = nn.ModuleList([\n",
        "            nn.Sequential(\n",
        "                nn.Linear(fusion_dim, fusion_dim // 2),\n",
        "                nn.LayerNorm(fusion_dim // 2),\n",
        "                nn.GELU(),\n",
        "                nn.Dropout(dropout * 0.5),\n",
        "                nn.Linear(fusion_dim // 2, 64),\n",
        "                nn.GELU(),\n",
        "                nn.Linear(64, 1)\n",
        "            ) for _ in range(num_targets)\n",
        "        ])\n",
        "\n",
        "    def extract_features(self, x):\n",
        "        f = self.backbone(x)\n",
        "        return f.mean(dim=1) if len(f.shape) == 3 else f.mean(dim=[2, 3]) if len(f.shape) == 4 else f\n",
        "\n",
        "    def forward(self, img_l, img_r):\n",
        "        f_l = self.extract_features(img_l)\n",
        "        f_r = self.extract_features(img_r)\n",
        "        tok = torch.stack([f_l, f_r], dim=1)\n",
        "        attn_out, _ = self.cross_view_attn(tok, tok, tok)\n",
        "        tok = self.attn_norm(tok + attn_out)\n",
        "        fused = self.fusion_mlp(torch.cat([tok[:, 0], tok[:, 1]], dim=-1))\n",
        "        return [F.softplus(h(fused)) for h in self.reg_heads]\n"
    ]

    # Cell 6: Fast 2-Stage Training
    nb['cells'][6]['source'] = [
        "# 6. Fast 2-Stage Training & Stratified Cross-Validation\n",
        "# 1. Load and pivot dataset\n",
        "raw_df = pd.read_csv(TRAIN_CSV)\n",
        "pivot_df = raw_df.pivot_table(\n",
        "    index=['image_path', 'Sampling_Date', 'State', 'Species', 'Pre_GSHH_NDVI', 'Height_Ave_cm'],\n",
        "    columns='target_name', values='target', aggfunc='first'\n",
        ").reset_index()\n",
        "id_map = raw_df.drop_duplicates('image_path').set_index('image_path')['sample_id'].to_dict()\n",
        "pivot_df['sample_id'] = pivot_df['image_path'].map(id_map)\n",
        "\n",
        "skf = StratifiedKFold(n_splits=CFG.N_FOLDS, shuffle=True, random_state=CFG.SEED)\n",
        "pivot_df['fold'] = -1\n",
        "for f, (tr, va) in enumerate(skf.split(pivot_df, y=pivot_df['State'])):\n",
        "    pivot_df.loc[va, 'fold'] = f\n",
        "\n",
        "print(f'Training on {len(pivot_df)} clean samples across {CFG.N_FOLDS} folds.')\n",
        "\n",
        "oof_preds = np.zeros((len(pivot_df), 5), dtype=np.float32)\n",
        "oof_targets = pivot_df[CFG.ALL_TARGETS].values\n",
        "fold_scores = []\n",
        "criterion = nn.SmoothL1Loss()\n",
        "\n",
        "for fold in range(CFG.N_FOLDS):\n",
        "    print(f'\\n========== FOLD {fold+1} / {CFG.N_FOLDS} ==========')\n",
        "    tr_df = pivot_df[pivot_df['fold'] != fold].reset_index(drop=True)\n",
        "    va_df = pivot_df[pivot_df['fold'] == fold].reset_index(drop=True)\n",
        "    va_idx = pivot_df[pivot_df['fold'] == fold].index.values\n",
        "\n",
        "    tr_loader = DataLoader(DualStreamDataset(tr_df, img_size=CFG.IMG_SIZE, is_train=True), batch_size=CFG.BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)\n",
        "    va_loader = DataLoader(DualStreamDataset(va_df, img_size=CFG.IMG_SIZE, is_train=False), batch_size=CFG.BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)\n",
        "\n",
        "    # Save sample batch for this fold\n",
        "    import matplotlib.pyplot as plt\n",
        "    sample_b = next(iter(tr_loader))\n",
        "    imgs_l, imgs_r = sample_b['img_l'].cpu(), sample_b['img_r'].cpu()\n",
        "    fig, axes = plt.subplots(min(len(imgs_l), 2), 2, figsize=(6, 6))\n",
        "    mean = np.array([0.485, 0.456, 0.406]).reshape(1, 1, 3)\n",
        "    std = np.array([0.229, 0.224, 0.225]).reshape(1, 1, 3)\n",
        "    for i in range(min(len(imgs_l), 2)):\n",
        "        rgb_l = np.clip(imgs_l[i].permute(1, 2, 0).numpy() * std + mean, 0, 1)\n",
        "        rgb_r = np.clip(imgs_r[i].permute(1, 2, 0).numpy() * std + mean, 0, 1)\n",
        "        axes[i, 0].imshow(rgb_l); axes[i, 0].axis('off'); axes[i, 0].set_title(f'Fold {fold+1} Left')\n",
        "        axes[i, 1].imshow(rgb_r); axes[i, 1].axis('off'); axes[i, 1].set_title(f'Fold {fold+1} Right')\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(os.path.join(OUTPUT_DIR, f'sample_batch_fold{fold+1}.png'), bbox_inches='tight')\n",
        "    plt.close()\n",
        "\n",
        "    model = DualStreamBiomassModel(backbone_name=CFG.BACKBONE, num_targets=3, pretrained=True).to(CFG.DEVICE)\n",
        "    scaler = torch.amp.GradScaler('cuda')\n",
        "    best_r2 = -float('inf')\n",
        "    best_preds = None\n",
        "\n",
        "    # STAGE 1: Warm up heads (backbone frozen)\n",
        "    for p in model.backbone.parameters(): p.requires_grad = False\n",
        "    opt = AdamW([p for p in model.parameters() if p.requires_grad], lr=CFG.LR, weight_decay=CFG.WEIGHT_DECAY)\n",
        "    sched = CosineAnnealingLR(opt, T_max=CFG.STAGE1_EPOCHS, eta_min=1e-5)\n",
        "    for ep in range(1, CFG.STAGE1_EPOCHS + 1):\n",
        "        model.train()\n",
        "        for b in tr_loader:\n",
        "            opt.zero_grad()\n",
        "            with torch.amp.autocast('cuda'):\n",
        "                preds = model(b['img_l'].to(CFG.DEVICE), b['img_r'].to(CFG.DEVICE))\n",
        "                loss = sum(criterion(p.squeeze(-1), b['targets'][:, i].to(CFG.DEVICE)) for i, p in enumerate(preds)) / 3.0\n",
        "            scaler.scale(loss).backward()\n",
        "            scaler.step(opt); scaler.update()\n",
        "        sched.step()\n",
        "\n",
        "    # STAGE 2: Full Fine-Tuning (backbone unfrozen)\n",
        "    for p in model.backbone.parameters(): p.requires_grad = True\n",
        "    opt = AdamW([\n",
        "        {'params': model.backbone.parameters(), 'lr': CFG.LR * CFG.BACKBONE_LR_FACTOR},\n",
        "        {'params': [p for n, p in model.named_parameters() if not n.startswith('backbone')], 'lr': CFG.LR}\n",
        "    ], weight_decay=CFG.WEIGHT_DECAY)\n",
        "    sched = CosineAnnealingLR(opt, T_max=CFG.STAGE2_EPOCHS, eta_min=CFG.LR * CFG.BACKBONE_LR_FACTOR * 0.05)\n",
        "\n",
        "    for ep in range(1, CFG.STAGE2_EPOCHS + 1):\n",
        "        model.train()\n",
        "        tr_loss = 0.0\n",
        "        for b in tr_loader:\n",
        "            opt.zero_grad()\n",
        "            with torch.amp.autocast('cuda'):\n",
        "                preds = model(b['img_l'].to(CFG.DEVICE), b['img_r'].to(CFG.DEVICE))\n",
        "                loss = sum(criterion(p.squeeze(-1), b['targets'][:, i].to(CFG.DEVICE)) for i, p in enumerate(preds)) / 3.0\n",
        "            scaler.scale(loss).backward()\n",
        "            scaler.step(opt); scaler.update()\n",
        "            tr_loss += loss.item() * len(b['targets'])\n",
        "        sched.step()\n",
        "\n",
        "        # Validation with TTA\n",
        "        model.eval()\n",
        "        va_preds = []\n",
        "        with torch.no_grad():\n",
        "            for b in va_loader:\n",
        "                l, r = b['img_l'].to(CFG.DEVICE), b['img_r'].to(CFG.DEVICE)\n",
        "                p1 = model(l, r)\n",
        "                p2 = model(torch.flip(r, [3]), torch.flip(l, [3]))\n",
        "                p_avg = [(r1 + r2) * 0.5 for r1, r2 in zip(p1, p2)]\n",
        "                va_preds.append(torch.cat(p_avg, dim=1).cpu().numpy())\n",
        "        va_preds_3 = np.concatenate(va_preds, axis=0)\n",
        "        va_preds_5 = derive_5_targets(va_preds_3)\n",
        "        va_post = apply_2nd_place_postprocess(va_preds_5, states=va_df['State'].values)\n",
        "        r2 = calculate_competition_r2(va_df[CFG.ALL_TARGETS].values, va_post)\n",
        "        print(f'[Ep {ep:02d}] Train: {tr_loss/len(tr_df):.4f} | Val R2: {r2:.4f}')\n",
        "        if r2 > best_r2:\n",
        "            best_r2 = r2\n",
        "            best_preds = va_post\n",
        "            torch.save(model.state_dict(), os.path.join(OUTPUT_DIR, f'best_model_fold{fold+1}.pt'))\n",
        "\n",
        "    oof_preds[va_idx] = best_preds\n",
        "    fold_scores.append(best_r2)\n",
        "    print(f'Fold {fold+1} Best R2: {best_r2:.4f}')\n",
        "\n",
        "total_oof_r2 = calculate_competition_r2(oof_targets, oof_preds)\n",
        "print(f'\\n========================================')\n",
        "print(f'FINAL 3-FOLD OOF COMPETITION R2: {total_oof_r2:.4f}')\n",
        "print(f'Per-fold scores: {[round(s, 4) for s in fold_scores]}')\n",
        "print(f'========================================')\n"
    ]

    with open(nb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
    print("Successfully updated src/notebooks/training.ipynb!")


def update_inference_notebook():
    nb_path = 'src/notebooks/inference.ipynb'
    with open(nb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # Cell 3: Smart Architecture Detector & Model Definition
    nb['cells'][3]['source'] = [
        "# 3. DualStreamBiomassModel Architecture & Universal Architecture Detector\n",
        "def detect_model_architecture(state_dict):\n",
        "    \"\"\"\n",
        "    Detects backbone architecture and head count from checkpoint state dict:\n",
        "    - dim 1536: ConvNeXt-V2 Large\n",
        "    - dim 768: DINOv3 ViT-Base\n",
        "    - dim 384: DINOv2 ViT-Small\n",
        "    \"\"\"\n",
        "    if isinstance(state_dict, dict) and 'state_dict' in state_dict:\n",
        "        state_dict = state_dict['state_dict']\n",
        "        \n",
        "    clean_sd = {k.replace('module.', ''): v for k, v in state_dict.items()}\n",
        "    \n",
        "    # Detect number of regression heads\n",
        "    reg_keys = [k for k in clean_sd.keys() if 'reg_heads.' in k and '.0.weight' in k]\n",
        "    num_targets = len(reg_keys) if len(reg_keys) > 0 else 5\n",
        "    \n",
        "    # Check embedding dimension\n",
        "    if 'cross_view_attn.in_proj_weight' in clean_sd:\n",
        "        dim = clean_sd['cross_view_attn.in_proj_weight'].shape[1]\n",
        "        if dim == 1536:\n",
        "            return 'convnextv2_large', num_targets, clean_sd\n",
        "        elif dim == 768:\n",
        "            return 'vit_base_patch16_dinov3_qkvb', num_targets, clean_sd\n",
        "        elif dim == 384:\n",
        "            return 'vit_small_patch14_dinov2', num_targets, clean_sd\n",
        "            \n",
        "    keys = list(clean_sd.keys())\n",
        "    if any('stages' in k for k in keys) or any('convnext' in k.lower() for k in keys):\n",
        "        return 'convnextv2_large', num_targets, clean_sd\n",
        "        \n",
        "    return 'vit_small_patch14_dinov2', num_targets, clean_sd\n",
        "\n",
        "class DualStreamBiomassModel(nn.Module):\n",
        "    def __init__(self, backbone_name='vit_small_patch14_dinov2', num_targets=3, num_intervals=7, fusion_dim=384, dropout=0.3, pretrained=False, **kwargs):\n",
        "        super().__init__()\n",
        "        self.backbone_name = backbone_name\n",
        "        extra = {'dynamic_img_size': True} if ('dinov2' in backbone_name or 'patch14' in backbone_name) else {}\n",
        "        self.backbone = timm.create_model(backbone_name, pretrained=pretrained, num_classes=0, **extra)\n",
        "        self.backbone_dim = self.backbone.num_features\n",
        "        \n",
        "        num_heads = 8 if self.backbone_dim % 8 == 0 else 4\n",
        "        self.cross_view_attn = nn.MultiheadAttention(embed_dim=self.backbone_dim, num_heads=num_heads, dropout=0.1, batch_first=True)\n",
        "        self.attn_norm = nn.LayerNorm(self.backbone_dim)\n",
        "        \n",
        "        self.fusion_mlp = nn.Sequential(\n",
        "            nn.Linear(self.backbone_dim * 2, fusion_dim),\n",
        "            nn.LayerNorm(fusion_dim),\n",
        "            nn.GELU(),\n",
        "            nn.Dropout(dropout)\n",
        "        )\n",
        "        \n",
        "        self.reg_heads = nn.ModuleList([\n",
        "            nn.Sequential(\n",
        "                nn.Linear(fusion_dim, fusion_dim // 2),\n",
        "                nn.LayerNorm(fusion_dim // 2),\n",
        "                nn.GELU(),\n",
        "                nn.Dropout(dropout * 0.5),\n",
        "                nn.Linear(fusion_dim // 2, 64),\n",
        "                nn.GELU(),\n",
        "                nn.Linear(64, 1)\n",
        "            ) for _ in range(num_targets)\n",
        "        ])\n",
        "\n",
        "    def extract_features(self, x):\n",
        "        feats = self.backbone(x)\n",
        "        return feats.mean(dim=1) if len(feats.shape) == 3 else feats.mean(dim=[2, 3]) if len(feats.shape) == 4 else feats\n",
        "\n",
        "    def forward(self, img_left, img_right):\n",
        "        feat_l = self.extract_features(img_left)\n",
        "        feat_r = self.extract_features(img_right)\n",
        "        tokens = torch.stack([feat_l, feat_r], dim=1)\n",
        "        attn_out, _ = self.cross_view_attn(tokens, tokens, tokens)\n",
        "        tokens = self.attn_norm(tokens + attn_out)\n",
        "        fused = self.fusion_mlp(torch.cat([tokens[:, 0], tokens[:, 1]], dim=-1))\n",
        "        return [F.softplus(head(fused)) for head in self.reg_heads]\n"
    ]

    # Cell 5: Post-Processing & Target Derivation functions
    nb['cells'][5]['source'] = [
        "# 5. Target Derivation & 2nd Place Post-Processing\n",
        "def derive_5_targets(preds_3):\n",
        "    green = preds_3[:, 0:1]\n",
        "    dead = preds_3[:, 1:2]\n",
        "    clover = preds_3[:, 2:3]\n",
        "    gdm = green + clover\n",
        "    total = green + dead + clover\n",
        "    return np.concatenate([green, dead, clover, gdm, total], axis=-1)\n",
        "\n",
        "def apply_2nd_place_postprocess(preds_5, states=None):\n",
        "    preds = np.maximum(preds_5.copy(), 0.0)\n",
        "    green = preds[:, 0].copy()\n",
        "    dead = preds[:, 1].copy()\n",
        "    clover = preds[:, 2].copy()\n",
        "    if states is not None:\n",
        "        for idx, st in enumerate(states):\n",
        "            st_str = str(st).strip()\n",
        "            if st_str == 'WA':\n",
        "                dead[idx] = 0.0\n",
        "                clover[idx] *= 0.80\n",
        "                green[idx] *= 0.97\n",
        "            elif st_str == 'Vic':\n",
        "                clover[idx] *= 0.85\n",
        "            elif st_str == 'NSW':\n",
        "                green[idx] *= 1.03\n",
        "    clover = np.clip(clover, 0.0, 71.7865)\n",
        "    dead = np.clip(dead, 0.0, 83.8407)\n",
        "    green = np.clip(green, 0.0, 157.9836)\n",
        "    gdm = green + clover\n",
        "    total = green + dead + clover\n",
        "    return np.column_stack([green, dead, clover, gdm, total])\n",
        "\n",
        "def soft_physics_postprocess(preds_np):\n",
        "    preds = np.maximum(preds_np.copy(), 0.0)\n",
        "    green = preds[:, 0]\n",
        "    dead = preds[:, 1]\n",
        "    clover = preds[:, 2] * 0.80\n",
        "    gdm = 0.5 * preds[:, 3] + 0.5 * (green + clover)\n",
        "    total = 0.5 * preds[:, 4] + 0.5 * (green + clover + dead)\n",
        "    return np.column_stack([green, dead, clover, gdm, total])\n"
    ]

    with open(nb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
    print("Successfully updated src/notebooks/inference.ipynb!")

if __name__ == '__main__':
    update_training_notebook()
    update_inference_notebook()
