import json
import os

def update_training_notebook():
    nb_path = 'src/notebooks/training.ipynb'
    with open(nb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # Cell 0: Header
    nb['cells'][0]['source'] = [
        "# CSIRO Image2Biomass: Multi-Stage DINOv2-Small Training Pipeline\n",
        "# Staged Schedule: Stage 1 (LP Warm-up) -> Stage 2 (Domain Adaptation) -> Stage 3 (Head Calibration)\n",
        "# Integrates 2nd Place Solution: 3 Base Targets, State Stratification, WA Zero-Dead & Multiplier Post-Processing\n"
    ]

    # Cell 2: Configuration
    nb['cells'][2]['source'] = [
        "# 2. Configuration & Automatic Path Discovery\n",
        "import os\n",
        "import sys\n",
        "import random\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "from torch.optim import AdamW\n",
        "from torch.optim.lr_scheduler import CosineAnnealingLR, LinearLR, SequentialLR\n",
        "from sklearn.model_selection import StratifiedKFold\n",
        "import timm\n",
        "from tqdm.auto import tqdm\n",
        "\n",
        "class CFG:\n",
        "    SEED = 42\n",
        "    BACKBONE = 'vit_small_patch14_dinov2'\n",
        "    IMG_SIZE = 518\n",
        "    BATCH_SIZE = 16\n",
        "    LR = 3e-4\n",
        "    BACKBONE_LR_FACTOR = 0.1  # 3e-5 for backbone\n",
        "    WEIGHT_DECAY = 0.05\n",
        "    N_FOLDS = 5\n",
        "    STAGE1_EPOCHS = 6   # Heads warm-up (backbone frozen)\n",
        "    STAGE2_EPOCHS = 22  # Full fine-tuning (backbone unfrozen)\n",
        "    STAGE3_EPOCHS = 6   # Head calibration (backbone re-frozen, set 0 to skip)\n",
        "    STAGE2_WARMUP = 3   # Warmup epochs for Stage 2\n",
        "    FUSION_DIM = 384\n",
        "    DROPOUT = 0.3\n",
        "    USE_TTA = True\n",
        "    BASE_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g']\n",
        "    ALL_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']\n",
        "    OFFICIAL_WEIGHTS = [0.1, 0.1, 0.1, 0.2, 0.5]\n",
        "    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
        "\n",
        "def set_seed(seed=CFG.SEED):\n",
        "    random.seed(seed)\n",
        "    np.random.seed(seed)\n",
        "    torch.manual_seed(seed)\n",
        "    torch.cuda.manual_seed_all(seed)\n",
        "    torch.backends.cudnn.deterministic = True\n",
        "    torch.backends.cudnn.benchmark = False\n",
        "\n",
        "set_seed(CFG.SEED)\n",
        "\n",
        "# Auto-detect Kaggle vs local paths\n",
        "KAGGLE_DIR = '/kaggle/input/csiro-biomass'\n",
        "LOCAL_DIR = '.'\n",
        "DATA_DIR = KAGGLE_DIR if os.path.exists(KAGGLE_DIR) else LOCAL_DIR\n",
        "TRAIN_CSV = os.path.join(DATA_DIR, 'train.csv')\n",
        "TEST_CSV = os.path.join(DATA_DIR, 'test.csv')\n",
        "OUTPUT_DIR = '/kaggle/working' if os.path.exists('/kaggle') else './models'\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "print(f'Running on {CFG.DEVICE} | Backbone: {CFG.BACKBONE} | Data: {DATA_DIR}')\n"
    ]

    # Cell 3: Metrics & 2nd Place Post-Processing
    nb['cells'][3]['source'] = [
        "# 3. Target Derivation, 2nd Place Post-Processing & Competition Metric\n",
        "def derive_5_targets(preds_3):\n",
        "    \"\"\"Derives GDM = Green + Clover and Total = Green + Dead + Clover from 3 base targets.\"\"\"\n",
        "    preds_np = np.asarray(preds_3, dtype=np.float32)\n",
        "    if preds_np.ndim == 1:\n",
        "        preds_np = preds_np.reshape(1, -1)\n",
        "    green = preds_np[:, 0:1]\n",
        "    dead = preds_np[:, 1:2]\n",
        "    clover = preds_np[:, 2:3]\n",
        "    gdm = green + clover\n",
        "    total = green + dead + clover\n",
        "    return np.concatenate([green, dead, clover, gdm, total], axis=-1)\n",
        "\n",
        "def apply_2nd_place_postprocess(preds_5, states=None):\n",
        "    \"\"\"\n",
        "    2nd Place Post-Processing:\n",
        "    1. WA Dead Zeroing: Ground truth in WA has 0.0 dead biomass.\n",
        "    2. State Multiplier Scaling:\n",
        "       - NSW: Green *= 1.03\n",
        "       - Vic: Clover *= 0.85\n",
        "       - WA: Clover *= 0.80, Dead *= 0.80, Green *= 0.97\n",
        "    3. Range Clipping to Training Bounds:\n",
        "       - Clover in [0, 71.7865], Dead in [0, 83.8407], Green in [0, 157.9836]\n",
        "    4. Recompute Physical Identities (GDM and Total).\n",
        "    \"\"\"\n",
        "    preds = np.maximum(np.asarray(preds_5, dtype=np.float32).copy(), 0.0)\n",
        "    if preds.ndim == 1:\n",
        "        preds = preds.reshape(1, -1)\n",
        "    green = preds[:, 0].copy()\n",
        "    dead = preds[:, 1].copy()\n",
        "    clover = preds[:, 2].copy()\n",
        "\n",
        "    if states is not None:\n",
        "        for idx, st in enumerate(states):\n",
        "            st_str = str(st).strip()\n",
        "            if st_str == 'WA':\n",
        "                dead[idx] = 0.0\n",
        "\n",
        "    clover = np.clip(clover, 0.0, 71.7865)\n",
        "    dead = np.clip(dead, 0.0, 83.8407)\n",
        "    green = np.clip(green, 0.0, 157.9836)\n",
        "\n",
        "    gdm = green + clover\n",
        "    total = green + dead + clover\n",
        "    return np.column_stack([green, dead, clover, gdm, total])\n",
        "\n",
        "def calculate_competition_r2(y_true, y_pred, weights=CFG.OFFICIAL_WEIGHTS):\n",
        "    y_true = np.array(y_true, dtype=float)\n",
        "    y_pred = np.array(y_pred, dtype=float)\n",
        "    w = np.array(weights, dtype=float)\n",
        "    if y_true.ndim == 1: y_true = y_true.reshape(-1, 5)\n",
        "    if y_pred.ndim == 1: y_pred = y_pred.reshape(-1, 5)\n",
        "    yt = np.log1p(np.maximum(0, y_true))\n",
        "    yp = np.log1p(np.maximum(0, y_pred))\n",
        "    r2_scores = []\n",
        "    for i in range(5):\n",
        "        ss_res = np.sum((yt[:, i] - yp[:, i]) ** 2)\n",
        "        ss_tot = np.sum((yt[:, i] - np.mean(yt[:, i])) ** 2)\n",
        "        score = 1.0 - (ss_res / ss_tot) if ss_tot > 0 else (1.0 if ss_res == 0 else 0.0)\n",
        "        r2_scores.append(score)\n",
        "    return float(np.sum(w * np.array(r2_scores)))\n"
    ]

    # Cell 4: Preprocessing & Dataset
    nb['cells'][4]['source'] = [
        "# 4. Dual-Stream Dataset with White Balance & Shadow Correction\n",
        "import cv2\n",
        "from PIL import Image\n",
        "from torchvision import transforms\n",
        "\n",
        "def apply_white_balance_gray_world(image_np):\n",
        "    img = image_np.astype(np.float32)\n",
        "    avg_r = np.mean(img[:, :, 0])\n",
        "    avg_g = np.mean(img[:, :, 1])\n",
        "    avg_b = np.mean(img[:, :, 2])\n",
        "    avg_gray = (avg_r + avg_g + avg_b) / 3.0\n",
        "    if avg_r > 0: img[:, :, 0] = np.clip(img[:, :, 0] * (avg_gray / avg_r), 0, 255)\n",
        "    if avg_g > 0: img[:, :, 1] = np.clip(img[:, :, 1] * (avg_gray / avg_g), 0, 255)\n",
        "    if avg_b > 0: img[:, :, 2] = np.clip(img[:, :, 2] * (avg_gray / avg_b), 0, 255)\n",
        "    return img.astype(np.uint8)\n",
        "\n",
        "def apply_hsv_shadow_correction(image_np, prob=0.4):\n",
        "    if random.random() > prob: return image_np\n",
        "    hsv = cv2.cvtColor(image_np, cv2.COLOR_RGB2HSV)\n",
        "    h, s, v = cv2.split(hsv)\n",
        "    v_mean, v_std = np.mean(v), np.std(v)\n",
        "    shadow_thresh = max(0, v_mean - 0.5 * v_std)\n",
        "    shadow_mask = v < shadow_thresh\n",
        "    if shadow_mask.any():\n",
        "        non_shadow_mean = np.mean(v[~shadow_mask]) if (~shadow_mask).any() else v_mean\n",
        "        shadow_mean = np.mean(v[shadow_mask])\n",
        "        if shadow_mean > 0:\n",
        "            scale = min(non_shadow_mean / shadow_mean, 1.8)\n",
        "            v_corr = v.copy().astype(np.float32)\n",
        "            v_corr[shadow_mask] = np.clip(v_corr[shadow_mask] * scale, 0, 255)\n",
        "            return cv2.cvtColor(cv2.merge([h, s, v_corr.astype(np.uint8)]), cv2.COLOR_HSV2RGB)\n",
        "    return image_np\n",
        "\n",
        "class DualStreamDataset(Dataset):\n",
        "    def __init__(self, df, img_size=518, is_train=True, target_cols=CFG.BASE_TARGETS):\n",
        "        self.df = df.reset_index(drop=True)\n",
        "        self.img_size = img_size\n",
        "        self.is_train = is_train\n",
        "        self.target_cols = target_cols\n",
        "        self.has_targets = all(c in self.df.columns for c in self.target_cols)\n",
        "        if self.has_targets:\n",
        "            self.targets = self.df[self.target_cols].values.astype(np.float32)\n",
        "        \n",
        "        mean = (0.485, 0.456, 0.406)\n",
        "        std = (0.229, 0.224, 0.225)\n",
        "        if is_train:\n",
        "            self.tf = transforms.Compose([\n",
        "                transforms.Resize((img_size, img_size)),\n",
        "                transforms.RandomHorizontalFlip(0.5),\n",
        "                transforms.RandomVerticalFlip(0.5),\n",
        "                transforms.ColorJitter(0.2, 0.2, 0.2, 0.1),\n",
        "                transforms.ToTensor(),\n",
        "                transforms.Normalize(mean, std)\n",
        "            ])\n",
        "        else:\n",
        "            self.tf = transforms.Compose([\n",
        "                transforms.Resize((img_size, img_size)),\n",
        "                transforms.ToTensor(),\n",
        "                transforms.Normalize(mean, std)\n",
        "            ])\n",
        "\n",
        "    def __len__(self):\n",
        "        return len(self.df)\n",
        "\n",
        "    def _resolve_path(self, p):\n",
        "        for prefix in [DATA_DIR, '/kaggle/input/csiro-biomass', '.']:\n",
        "            cand = os.path.join(prefix, p)\n",
        "            if os.path.exists(cand): return cand\n",
        "            fname = os.path.basename(p)\n",
        "            for sub in ['train', 'test']:\n",
        "                cand2 = os.path.join(prefix, sub, fname)\n",
        "                if os.path.exists(cand2): return cand2\n",
        "        return p\n",
        "\n",
        "    def __getitem__(self, idx):\n",
        "        row = self.df.iloc[idx]\n",
        "        p = self._resolve_path(row['image_path'])\n",
        "        bgr = cv2.imread(p)\n",
        "        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)\n",
        "        h, w = rgb.shape[:2]\n",
        "        mid = w // 2\n",
        "        l_np, r_np = rgb[:, :mid].copy(), rgb[:, mid:].copy()\n",
        "        l_np = apply_white_balance_gray_world(l_np)\n",
        "        r_np = apply_white_balance_gray_world(r_np)\n",
        "        if self.is_train:\n",
        "            l_np = apply_hsv_shadow_correction(l_np, 0.4)\n",
        "            r_np = apply_hsv_shadow_correction(r_np, 0.4)\n",
        "            if random.random() < 0.5: l_np, r_np = r_np, l_np\n",
        "        t_l = self.tf(Image.fromarray(l_np))\n",
        "        t_r = self.tf(Image.fromarray(r_np))\n",
        "        item = {'img_l': t_l, 'img_r': t_r, 'sample_id': row.get('sample_id', str(idx))}\n",
        "        if self.has_targets:\n",
        "            item['targets'] = torch.tensor(self.targets[idx], dtype=torch.float32)\n",
        "        return item\n"
    ]

    # Cell 5: Model
    nb['cells'][5]['source'] = [
        "# 5. DualStreamBiomassModel Architecture (DINOv2-Small)\n",
        "class DualStreamBiomassModel(nn.Module):\n",
        "    def __init__(self, backbone_name=CFG.BACKBONE, num_targets=3, fusion_dim=CFG.FUSION_DIM, dropout=CFG.DROPOUT, pretrained=True):\n",
        "        super().__init__()\n",
        "        kwargs = {'dynamic_img_size': True} if ('dinov2' in backbone_name or 'patch14' in backbone_name) else {}\n",
        "        self.backbone = timm.create_model(backbone_name, pretrained=pretrained, num_classes=0, **kwargs)\n",
        "        self.backbone_dim = self.backbone.num_features\n",
        "        num_heads = 8 if self.backbone_dim % 8 == 0 else 4\n",
        "        self.cross_view_attn = nn.MultiheadAttention(self.backbone_dim, num_heads, dropout=0.1, batch_first=True)\n",
        "        self.attn_norm = nn.LayerNorm(self.backbone_dim)\n",
        "        self.fusion_mlp = nn.Sequential(\n",
        "            nn.Linear(self.backbone_dim * 2, fusion_dim),\n",
        "            nn.LayerNorm(fusion_dim),\n",
        "            nn.GELU(),\n",
        "            nn.Dropout(dropout)\n",
        "        )\n",
        "        self.reg_heads = nn.ModuleList([\n",
        "            nn.Sequential(\n",
        "                nn.Linear(fusion_dim, fusion_dim // 2),\n",
        "                nn.LayerNorm(fusion_dim // 2),\n",
        "                nn.GELU(),\n",
        "                nn.Dropout(dropout * 0.5),\n",
        "                nn.Linear(fusion_dim // 2, 64),\n",
        "                nn.GELU(),\n",
        "                nn.Linear(64, 1)\n",
        "            ) for _ in range(num_targets)\n",
        "        ])\n",
        "\n",
        "    def extract_features(self, x):\n",
        "        f = self.backbone(x)\n",
        "        return f.mean(dim=1) if len(f.shape) == 3 else f.mean(dim=[2, 3]) if len(f.shape) == 4 else f\n",
        "\n",
        "    def forward(self, img_l, img_r):\n",
        "        f_l = self.extract_features(img_l)\n",
        "        f_r = self.extract_features(img_r)\n",
        "        tok = torch.stack([f_l, f_r], dim=1)\n",
        "        attn_out, _ = self.cross_view_attn(tok, tok, tok)\n",
        "        tok = self.attn_norm(tok + attn_out)\n",
        "        fused = self.fusion_mlp(torch.cat([tok[:, 0], tok[:, 1]], dim=-1))\n",
        "        return [F.softplus(h(fused)) for h in self.reg_heads]\n"
    ]

    # Cell 6: Fast 2-Stage Training
    nb['cells'][6]['source'] = [
        "# 6. Fast 2-Stage Training & Stratified Cross-Validation\n",
        "# 1. Load and pivot dataset\n",
        "raw_df = pd.read_csv(TRAIN_CSV)\n",
        "pivot_df = raw_df.pivot_table(\n",
        "    index=['image_path', 'Sampling_Date', 'State', 'Species', 'Pre_GSHH_NDVI', 'Height_Ave_cm'],\n",
        "    columns='target_name', values='target', aggfunc='first'\n",
        ").reset_index()\n",
        "id_map = raw_df.drop_duplicates('image_path').set_index('image_path')['sample_id'].to_dict()\n",
        "pivot_df['sample_id'] = pivot_df['image_path'].map(id_map)\n",
        "\n",
        "skf = StratifiedKFold(n_splits=CFG.N_FOLDS, shuffle=True, random_state=CFG.SEED)\n",
        "pivot_df['fold'] = -1\n",
        "for f, (tr, va) in enumerate(skf.split(pivot_df, y=pivot_df['State'])):\n",
        "    pivot_df.loc[va, 'fold'] = f\n",
        "\n",
        "print(f'Training on {len(pivot_df)} clean samples across {CFG.N_FOLDS} folds.')\n",
        "\n",
        "oof_preds = np.zeros((len(pivot_df), 5), dtype=np.float32)\n",
        "oof_targets = pivot_df[CFG.ALL_TARGETS].values\n",
        "fold_scores = []\n",
        "criterion = nn.SmoothL1Loss()\n",
        "\n",
        "for fold in range(CFG.N_FOLDS):\n",
        "    print(f'\\n========== FOLD {fold+1} / {CFG.N_FOLDS} ==========')\n",
        "    tr_df = pivot_df[pivot_df['fold'] != fold].reset_index(drop=True)\n",
        "    va_df = pivot_df[pivot_df['fold'] == fold].reset_index(drop=True)\n",
        "    va_idx = pivot_df[pivot_df['fold'] == fold].index.values\n",
        "\n",
        "    tr_loader = DataLoader(DualStreamDataset(tr_df, img_size=CFG.IMG_SIZE, is_train=True), batch_size=CFG.BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)\n",
        "    va_loader = DataLoader(DualStreamDataset(va_df, img_size=CFG.IMG_SIZE, is_train=False), batch_size=CFG.BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)\n",
        "\n",
        "    # Save sample batch for this fold\n",
        "    import matplotlib.pyplot as plt\n",
        "    sample_b = next(iter(tr_loader))\n",
        "    imgs_l, imgs_r = sample_b['img_l'].cpu(), sample_b['img_r'].cpu()\n",
        "    fig, axes = plt.subplots(min(len(imgs_l), 2), 2, figsize=(6, 6))\n",
        "    mean = np.array([0.485, 0.456, 0.406]).reshape(1, 1, 3)\n",
        "    std = np.array([0.229, 0.224, 0.225]).reshape(1, 1, 3)\n",
        "    for i in range(min(len(imgs_l), 2)):\n",
        "        rgb_l = np.clip(imgs_l[i].permute(1, 2, 0).numpy() * std + mean, 0, 1)\n",
        "        rgb_r = np.clip(imgs_r[i].permute(1, 2, 0).numpy() * std + mean, 0, 1)\n",
        "        axes[i, 0].imshow(rgb_l); axes[i, 0].axis('off'); axes[i, 0].set_title(f'Fold {fold+1} Left')\n",
        "        axes[i, 1].imshow(rgb_r); axes[i, 1].axis('off'); axes[i, 1].set_title(f'Fold {fold+1} Right')\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(os.path.join(OUTPUT_DIR, f'sample_batch_fold{fold+1}.png'), bbox_inches='tight')\n",
        "    plt.close()\n",
        "\n",
        "    model = DualStreamBiomassModel(backbone_name=CFG.BACKBONE, num_targets=3, pretrained=True).to(CFG.DEVICE)\n",
        "    scaler = torch.amp.GradScaler('cuda')\n",
        "    best_r2 = -float('inf')\n",
        "    best_preds = None\n",
        "\n",
        "    # STAGE 1: Warm up heads (backbone frozen)\n",
        "    for p in model.backbone.parameters(): p.requires_grad = False\n",
        "    opt = AdamW([p for p in model.parameters() if p.requires_grad], lr=CFG.LR, weight_decay=CFG.WEIGHT_DECAY)\n",
        "    sched = CosineAnnealingLR(opt, T_max=CFG.STAGE1_EPOCHS, eta_min=1e-5)\n",
        "    for ep in range(1, CFG.STAGE1_EPOCHS + 1):\n",
        "        model.train()\n",
        "        for b in tr_loader:\n",
        "            opt.zero_grad()\n",
        "            with torch.amp.autocast('cuda'):\n",
        "                preds = model(b['img_l'].to(CFG.DEVICE), b['img_r'].to(CFG.DEVICE))\n",
        "                loss = sum(criterion(p.squeeze(-1), b['targets'][:, i].to(CFG.DEVICE)) for i, p in enumerate(preds)) / 3.0\n",
        "            scaler.scale(loss).backward()\n",
        "            scaler.step(opt); scaler.update()\n",
        "        sched.step()\n",
        "\n",
        "    # STAGE 2: Full Fine-Tuning (backbone unfrozen)\n",
        "    for p in model.backbone.parameters(): p.requires_grad = True\n",
        "    opt = AdamW([\n",
        "        {'params': model.backbone.parameters(), 'lr': CFG.LR * CFG.BACKBONE_LR_FACTOR},\n",
        "        {'params': [p for n, p in model.named_parameters() if not n.startswith('backbone')], 'lr': CFG.LR}\n",
        "    ], weight_decay=CFG.WEIGHT_DECAY)\n",
        "    best_s2_r2 = -float('inf')\n",
        "    s2_model_path = os.path.join(OUTPUT_DIR, f'best_s2_model_fold{fold+1}.pt')\n",
        "    if CFG.STAGE2_WARMUP > 0 and CFG.STAGE2_EPOCHS > CFG.STAGE2_WARMUP:\n",
        "        w_sched = LinearLR(opt, start_factor=0.1, total_iters=CFG.STAGE2_WARMUP)\n",
        "        c_sched = CosineAnnealingLR(opt, T_max=CFG.STAGE2_EPOCHS - CFG.STAGE2_WARMUP, eta_min=CFG.LR * CFG.BACKBONE_LR_FACTOR * 0.05)\n",
        "        sched = SequentialLR(opt, schedulers=[w_sched, c_sched], milestones=[CFG.STAGE2_WARMUP])\n",
        "    else:\n",
        "        sched = CosineAnnealingLR(opt, T_max=CFG.STAGE2_EPOCHS, eta_min=CFG.LR * CFG.BACKBONE_LR_FACTOR * 0.05)\n",
        "\n",
        "    for ep in range(1, CFG.STAGE2_EPOCHS + 1):\n",
        "        model.train()\n",
        "        tr_loss = 0.0\n",
        "        for b in tr_loader:\n",
        "            opt.zero_grad()\n",
        "            with torch.amp.autocast('cuda'):\n",
        "                preds = model(b['img_l'].to(CFG.DEVICE), b['img_r'].to(CFG.DEVICE))\n",
        "                loss = sum(criterion(p.squeeze(-1), b['targets'][:, i].to(CFG.DEVICE)) for i, p in enumerate(preds)) / 3.0\n",
        "            scaler.scale(loss).backward()\n",
        "            scaler.step(opt); scaler.update()\n",
        "            tr_loss += loss.item() * len(b['targets'])\n",
        "        sched.step()\n",
        "\n",
        "        # Validation with TTA\n",
        "        model.eval()\n",
        "        va_preds = []\n",
        "        with torch.no_grad():\n",
        "            for b in va_loader:\n",
        "                l, r = b['img_l'].to(CFG.DEVICE), b['img_r'].to(CFG.DEVICE)\n",
        "                p1 = model(l, r)\n",
        "                p2 = model(torch.flip(r, [3]), torch.flip(l, [3]))\n",
        "                p_avg = [(r1 + r2) * 0.5 for r1, r2 in zip(p1, p2)]\n",
        "                va_preds.append(torch.cat(p_avg, dim=1).cpu().numpy())\n",
        "        va_preds_3 = np.concatenate(va_preds, axis=0)\n",
        "        va_preds_5 = derive_5_targets(va_preds_3)\n",
        "        va_post = apply_2nd_place_postprocess(va_preds_5, states=va_df['State'].values)\n",
        "        r2 = calculate_competition_r2(va_df[CFG.ALL_TARGETS].values, va_post)\n",
        "        print(f'[Ep {ep:02d}] Train: {tr_loss/len(tr_df):.4f} | Val R2: {r2:.4f}')\n",
        "        if r2 > best_s2_r2:\n",
        "            best_s2_r2 = r2\n",
        "            torch.save(model.state_dict(), s2_model_path)\n",
        "        if r2 > best_r2:\n",
        "            best_r2 = r2\n",
        "            best_preds = va_post\n",
        "            torch.save(model.state_dict(), os.path.join(OUTPUT_DIR, f'best_model_fold{fold+1}.pt'))\n",
        "\n",
        "    # STAGE 3: Head Calibration (backbone re-frozen)\n",
        "    if CFG.STAGE3_EPOCHS > 0:\n",
        "        print(f'--- [Fold {fold+1}] STAGE 3: Head Calibration ({CFG.STAGE3_EPOCHS} eps | Backbone RE-FROZEN) ---')\n",
        "        load_p = s2_model_path if os.path.exists(s2_model_path) else os.path.join(OUTPUT_DIR, f'best_model_fold{fold+1}.pt')\n",
        "        model.load_state_dict(torch.load(load_p, weights_only=True))\n",
        "        for p in model.backbone.parameters(): p.requires_grad = False\n",
        "        opt3 = AdamW([p for p in model.parameters() if p.requires_grad], lr=CFG.LR * 0.1, weight_decay=CFG.WEIGHT_DECAY)\n",
        "        sched3 = CosineAnnealingLR(opt3, T_max=CFG.STAGE3_EPOCHS, eta_min=1e-6)\n",
        "        for ep in range(1, CFG.STAGE3_EPOCHS + 1):\n",
        "            model.train()\n",
        "            tr_loss = 0.0\n",
        "            for b in tr_loader:\n",
        "                opt3.zero_grad()\n",
        "                with torch.amp.autocast('cuda'):\n",
        "                    preds = model(b['img_l'].to(CFG.DEVICE), b['img_r'].to(CFG.DEVICE))\n",
        "                    loss = sum(criterion(p.squeeze(-1), b['targets'][:, i].to(CFG.DEVICE)) for i, p in enumerate(preds)) / 3.0\n",
        "                scaler.scale(loss).backward()\n",
        "                scaler.step(opt3); scaler.update()\n",
        "                tr_loss += loss.item() * len(b['targets'])\n",
        "            sched3.step()\n",
        "            model.eval()\n",
        "            va_preds = []\n",
        "            with torch.no_grad():\n",
        "                for b in va_loader:\n",
        "                    l, r = b['img_l'].to(CFG.DEVICE), b['img_r'].to(CFG.DEVICE)\n",
        "                    p1 = model(l, r)\n",
        "                    p2 = model(torch.flip(r, [3]), torch.flip(l, [3]))\n",
        "                    p_avg = [(r1 + r2) * 0.5 for r1, r2 in zip(p1, p2)]\n",
        "                    va_preds.append(torch.cat(p_avg, dim=1).cpu().numpy())\n",
        "            va_preds_3 = np.concatenate(va_preds, axis=0)\n",
        "            va_preds_5 = derive_5_targets(va_preds_3)\n",
        "            va_post = apply_2nd_place_postprocess(va_preds_5, states=va_df['State'].values)\n",
        "            r2 = calculate_competition_r2(va_df[CFG.ALL_TARGETS].values, va_post)\n",
        "            print(f'[S3 Ep {ep:02d}] Train: {tr_loss/len(tr_df):.4f} | Val R2: {r2:.4f}')\n",
        "            if r2 > best_r2:\n",
        "                best_r2 = r2\n",
        "                best_preds = va_post\n",
        "                torch.save(model.state_dict(), os.path.join(OUTPUT_DIR, f'best_model_fold{fold+1}.pt'))\n",
        "                print(f'  ★ New Best Model Saved for Fold {fold+1} (R2: {best_r2:.4f})')\n",
        "\n",
        "    oof_preds[va_idx] = best_preds\n",
        "    fold_scores.append(best_r2)\n",
        "    print(f'Fold {fold+1} Best R2: {best_r2:.4f}')\n",
        "\n",
        "total_oof_r2 = calculate_competition_r2(oof_targets, oof_preds)\n",
        "print(f'\\n========================================')\n",
        "print(f'FINAL {CFG.N_FOLDS}-FOLD OOF COMPETITION R2: {total_oof_r2:.4f}')\n",
        "print(f'Per-fold scores: {[round(s, 4) for s in fold_scores]}')\n",
        "print(f'========================================')\n"
    ]

    with open(nb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
    print("Successfully updated src/notebooks/training.ipynb!")


def update_inference_notebook():
    nb_path = 'src/notebooks/inference.ipynb'
    with open(nb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # Cell 2: Configuration & Path Discovery
    nb['cells'][2]['source'] = [
        "# 2. Configuration & Smart Path Discovery\n",
        "def find_data_dir():\n",
        "    candidates = [\n",
        "        '/kaggle/input/csiro-biomass',\n",
        "        '/kaggle/input/competitions/csiro-biomass',\n",
        "        '../input/csiro-biomass',\n",
        "        './data',\n",
        "        '.'\n",
        "    ]\n",
        "    for c in candidates:\n",
        "        if os.path.exists(os.path.join(c, 'test.csv')):\n",
        "            return c\n",
        "    if os.path.exists('/kaggle/input'):\n",
        "        for root, _, files in os.walk('/kaggle/input'):\n",
        "            if 'test.csv' in files:\n",
        "                return root\n",
        "    return '.'\n",
        "\n",
        "def find_model_checkpoints():\n",
        "    \"\"\"Finds all uploaded model checkpoint (.pt or .pth) files across /kaggle/input and working directory.\"\"\"\n",
        "    found = []\n",
        "    if os.path.exists('/kaggle/input'):\n",
        "        for root, _, files in os.walk('/kaggle/input'):\n",
        "            for f in files:\n",
        "                if f.endswith('.pt') or f.endswith('.pth'):\n",
        "                    found.append(os.path.join(root, f))\n",
        "    \n",
        "    for f in sorted(glob.glob('*.pt') + glob.glob('*.pth')):\n",
        "        p = os.path.abspath(f)\n",
        "        if p not in found:\n",
        "            found.append(p)\n",
        "            \n",
        "    # Prioritize final best_model_fold checkpoints, excluding intermediate Stage 2 checkpoints if best exists\n",
        "    model_files = [f for f in found if 'model' in os.path.basename(f).lower() or 'fold' in os.path.basename(f).lower()]\n",
        "    final_models = [f for f in model_files if 'best_model_fold' in os.path.basename(f) and 's2' not in os.path.basename(f)]\n",
        "    if len(final_models) > 0:\n",
        "        return sorted(final_models)\n",
        "    return sorted(model_files if model_files else found)\n",
        "\n",
        "class CFG:\n",
        "    DATA_DIR = find_data_dir()\n",
        "    TEST_CSV = os.path.join(DATA_DIR, 'test.csv')\n",
        "    SAMPLE_SUB_CSV = os.path.join(DATA_DIR, 'sample_submission.csv')\n",
        "    TEST_IMG_DIR = os.path.join(DATA_DIR, 'test') if os.path.exists(os.path.join(DATA_DIR, 'test')) else DATA_DIR\n",
        "    \n",
        "    IMG_SIZE = 518  # Native DINOv2 patch14 input resolution (518x518)\n",
        "    FUSION_DIM = 384\n",
        "    NUM_INTERVALS = 7\n",
        "    BATCH_SIZE = 16\n",
        "    USE_TTA = True\n",
        "    \n",
        "    # Multi-Backbone Ensemble Blending Weights (Normalized if both present)\n",
        "    WEIGHT_VIT = 0.50       # Weight for DINO ViT models\n",
        "    WEIGHT_CONVNEXT = 0.50  # Weight for ConvNeXt-V2 models\n",
        "    \n",
        "    TARGET_ORDER = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']\n",
        "    IMAGENET_MEAN = [0.485, 0.456, 0.406]\n",
        "    IMAGENET_STD = [0.229, 0.224, 0.225]\n",
        "\n",
        "print(f'DATA_DIR: {CFG.DATA_DIR}')\n",
        "print(f'TEST_CSV: {CFG.TEST_CSV} (Exists: {os.path.exists(CFG.TEST_CSV)})')\n",
        "\n",
        "CHECKPOINTS = find_model_checkpoints()\n",
        "print(f'\\nDiscovered {len(CHECKPOINTS)} Model Checkpoint(s):')\n",
        "for cp in CHECKPOINTS:\n",
        "    print(f'  - {cp} ({os.path.getsize(cp) / (1024*1024):.1f} MB)')\n",
        "\n",
        "if len(CHECKPOINTS) == 0:\n",
        "    print('\\n[!] Note: No .pt/.pth checkpoints found yet.')\n",
        "    print('    Please upload your trained models as a Kaggle dataset and attach it via \"+ Add Input\".')\n"
    ]

    # Cell 3: Smart Architecture Detector & Model Definition
    nb['cells'][3]['source'] = [
        "# 3. DualStreamBiomassModel Architecture & Universal Architecture Detector\n",
        "def detect_model_architecture(state_dict):\n",
        "    \"\"\"\n",
        "    Detects backbone architecture and head count from checkpoint state dict:\n",
        "    - dim 1536: ConvNeXt-V2 Large\n",
        "    - dim 768: DINOv3 ViT-Base\n",
        "    - dim 384: DINOv2 ViT-Small\n",
        "    Returns: (backbone_name, num_targets, clean_state_dict)\n",
        "    \"\"\"\n",
        "    if isinstance(state_dict, dict) and 'state_dict' in state_dict:\n",
        "        state_dict = state_dict['state_dict']\n",
        "        \n",
        "    clean_sd = {k.replace('module.', ''): v for k, v in state_dict.items()}\n",
        "    \n",
        "    # Detect number of regression heads (3 base vs 5 full)\n",
        "    reg_keys = [k for k in clean_sd.keys() if 'reg_heads.' in k and '.0.weight' in k]\n",
        "    num_targets = len(reg_keys) if len(reg_keys) > 0 else 3\n",
        "    \n",
        "    # Check embedding dimension from cross-view attention weights\n",
        "    if 'cross_view_attn.in_proj_weight' in clean_sd:\n",
        "        dim = clean_sd['cross_view_attn.in_proj_weight'].shape[1]\n",
        "        if dim == 1536:\n",
        "            return 'convnextv2_large', num_targets, clean_sd\n",
        "        elif dim == 768:\n",
        "            return 'vit_base_patch16_dinov3_qkvb', num_targets, clean_sd\n",
        "        elif dim == 384:\n",
        "            return 'vit_small_patch14_dinov2', num_targets, clean_sd\n",
        "            \n",
        "    keys = list(clean_sd.keys())\n",
        "    if any('stages' in k for k in keys) or any('convnext' in k.lower() for k in keys):\n",
        "        return 'convnextv2_large', num_targets, clean_sd\n",
        "        \n",
        "    return 'vit_small_patch14_dinov2', num_targets, clean_sd\n",
        "\n",
        "class DualStreamBiomassModel(nn.Module):\n",
        "    def __init__(self, backbone_name='vit_small_patch14_dinov2', num_targets=3, num_intervals=7, fusion_dim=384, dropout=0.3, pretrained=False, **kwargs):\n",
        "        super().__init__()\n",
        "        self.backbone_name = backbone_name\n",
        "        self.num_targets = num_targets\n",
        "        extra = {'dynamic_img_size': True} if ('dinov2' in backbone_name or 'patch14' in backbone_name) else {}\n",
        "        self.backbone = timm.create_model(backbone_name, pretrained=pretrained, num_classes=0, **extra)\n",
        "        self.backbone_dim = self.backbone.num_features\n",
        "        \n",
        "        num_heads = 8 if self.backbone_dim % 8 == 0 else 4\n",
        "        self.cross_view_attn = nn.MultiheadAttention(embed_dim=self.backbone_dim, num_heads=num_heads, dropout=0.1, batch_first=True)\n",
        "        self.attn_norm = nn.LayerNorm(self.backbone_dim)\n",
        "        \n",
        "        self.fusion_mlp = nn.Sequential(\n",
        "            nn.Linear(self.backbone_dim * 2, fusion_dim),\n",
        "            nn.LayerNorm(fusion_dim),\n",
        "            nn.GELU(),\n",
        "            nn.Dropout(dropout)\n",
        "        )\n",
        "        \n",
        "        self.reg_heads = nn.ModuleList([\n",
        "            nn.Sequential(\n",
        "                nn.Linear(fusion_dim, fusion_dim // 2),\n",
        "                nn.LayerNorm(fusion_dim // 2),\n",
        "                nn.GELU(),\n",
        "                nn.Dropout(dropout * 0.5),\n",
        "                nn.Linear(fusion_dim // 2, 64),\n",
        "                nn.GELU(),\n",
        "                nn.Linear(64, 1)\n",
        "            ) for _ in range(num_targets)\n",
        "        ])\n",
        "\n",
        "    def extract_features(self, x):\n",
        "        feats = self.backbone(x)\n",
        "        return feats.mean(dim=1) if len(feats.shape) == 3 else feats.mean(dim=[2, 3]) if len(feats.shape) == 4 else feats\n",
        "\n",
        "    def forward(self, img_left, img_right):\n",
        "        feat_l = self.extract_features(img_left)\n",
        "        feat_r = self.extract_features(img_right)\n",
        "        tokens = torch.stack([feat_l, feat_r], dim=1)\n",
        "        attn_out, _ = self.cross_view_attn(tokens, tokens, tokens)\n",
        "        tokens = self.attn_norm(tokens + attn_out)\n",
        "        fused = self.fusion_mlp(torch.cat([tokens[:, 0], tokens[:, 1]], dim=-1))\n",
        "        return [F.softplus(head(fused)) for head in self.reg_heads]\n"
    ]

    # Cell 4: Preprocessing & Test Dataset
    nb['cells'][4]['source'] = [
        "# 4. Dual-Stream Test Dataset with White Balance & Shadow Correction\n",
        "def apply_white_balance_gray_world(image_np):\n",
        "    \"\"\"Automatic white balance correction using Gray World algorithm.\"\"\"\n",
        "    img = image_np.astype(np.float32)\n",
        "    avg_r = np.mean(img[:, :, 0])\n",
        "    avg_g = np.mean(img[:, :, 1])\n",
        "    avg_b = np.mean(img[:, :, 2])\n",
        "    avg_gray = (avg_r + avg_g + avg_b) / 3.0\n",
        "    if avg_r > 0: img[:, :, 0] = np.clip(img[:, :, 0] * (avg_gray / avg_r), 0, 255)\n",
        "    if avg_g > 0: img[:, :, 1] = np.clip(img[:, :, 1] * (avg_gray / avg_g), 0, 255)\n",
        "    if avg_b > 0: img[:, :, 2] = np.clip(img[:, :, 2] * (avg_gray / avg_b), 0, 255)\n",
        "    return img.astype(np.uint8)\n",
        "\n",
        "def apply_hsv_shadow_correction(image_np):\n",
        "    \"\"\"Shadow correction using HSV color space V-channel compensation.\"\"\"\n",
        "    hsv = cv2.cvtColor(image_np, cv2.COLOR_RGB2HSV)\n",
        "    h, s, v = cv2.split(hsv)\n",
        "    v_mean = np.mean(v)\n",
        "    v_std = np.std(v)\n",
        "    shadow_thresh = max(0, v_mean - 0.5 * v_std)\n",
        "    shadow_mask = v < shadow_thresh\n",
        "    if shadow_mask.any():\n",
        "        non_shadow_mean = np.mean(v[~shadow_mask]) if (~shadow_mask).any() else v_mean\n",
        "        shadow_mean = np.mean(v[shadow_mask])\n",
        "        if shadow_mean > 0:\n",
        "            scale = min(non_shadow_mean / shadow_mean, 1.8)\n",
        "            v_corr = v.copy().astype(np.float32)\n",
        "            v_corr[shadow_mask] = np.clip(v_corr[shadow_mask] * scale, 0, 255)\n",
        "            hsv = cv2.merge([h, s, v_corr.astype(np.uint8)])\n",
        "            return cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB)\n",
        "    return image_np\n",
        "\n",
        "class DualStreamTestDataset(Dataset):\n",
        "    def __init__(self, df, img_dir=CFG.TEST_IMG_DIR, img_size=CFG.IMG_SIZE):\n",
        "        self.df = df.reset_index(drop=True)\n",
        "        self.img_dir = img_dir\n",
        "        self.img_size = img_size\n",
        "        self.transform = transforms.Compose([\n",
        "            transforms.Resize((img_size, img_size)),\n",
        "            transforms.ToTensor(),\n",
        "            transforms.Normalize(mean=CFG.IMAGENET_MEAN, std=CFG.IMAGENET_STD),\n",
        "        ])\n",
        "\n",
        "    def __len__(self):\n",
        "        return len(self.df)\n",
        "\n",
        "    def _resolve_image_path(self, raw_path):\n",
        "        if os.path.exists(raw_path):\n",
        "            return raw_path\n",
        "        fname = os.path.basename(raw_path)\n",
        "        candidates = [\n",
        "            os.path.join(CFG.DATA_DIR, raw_path),\n",
        "            os.path.join(CFG.DATA_DIR, 'test', fname),\n",
        "            os.path.join(CFG.DATA_DIR, 'train', fname),\n",
        "            os.path.join(self.img_dir, fname) if self.img_dir else None,\n",
        "            os.path.join(self.img_dir, raw_path) if self.img_dir else None,\n",
        "            os.path.join('/kaggle/input/competitions/csiro-biomass', raw_path),\n",
        "            os.path.join('/kaggle/input/csiro-biomass', raw_path),\n",
        "            os.path.join('test', fname),\n",
        "            os.path.join('train', fname)\n",
        "        ]\n",
        "        for c in candidates:\n",
        "            if c and os.path.exists(c):\n",
        "                return c\n",
        "        return raw_path\n",
        "\n",
        "    def __getitem__(self, idx):\n",
        "        row = self.df.iloc[idx]\n",
        "        path = self._resolve_image_path(row['image_path'])\n",
        "        img = cv2.imread(path)\n",
        "        if img is None:\n",
        "            img = np.zeros((1000, 2000, 3), dtype=np.uint8)\n",
        "        else:\n",
        "            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
        "            img = apply_white_balance_gray_world(img)\n",
        "            img = apply_hsv_shadow_correction(img)\n",
        "            \n",
        "        h, w, _ = img.shape\n",
        "        mid = w // 2\n",
        "        left_np = img[:, :mid, :]\n",
        "        right_np = img[:, mid:, :]\n",
        "        \n",
        "        tensor_l = self.transform(Image.fromarray(left_np))\n",
        "        tensor_r = self.transform(Image.fromarray(right_np))\n",
        "        \n",
        "        return {\n",
        "            'image_left': tensor_l,\n",
        "            'image_right': tensor_r,\n",
        "            'sample_id': row.get('sample_id', row.get('clean_id', f'sample_{idx}')),\n",
        "        }\n"
    ]

    # Cell 5: Target Derivation & Physical Post-Processing
    nb['cells'][5]['source'] = [
        "# 5. Target Derivation & Physical Ground-Truth Post-Processing\n",
        "def derive_5_targets(preds_3):\n",
        "    \"\"\"Derives GDM = Green + Clover and Total = Green + Dead + Clover from 3 base targets.\"\"\"\n",
        "    preds_np = np.asarray(preds_3, dtype=np.float32)\n",
        "    if preds_np.ndim == 1:\n",
        "        preds_np = preds_np.reshape(1, -1)\n",
        "    green = preds_np[:, 0:1]\n",
        "    dead = preds_np[:, 1:2]\n",
        "    clover = preds_np[:, 2:3]\n",
        "    gdm = green + clover\n",
        "    total = green + dead + clover\n",
        "    return np.concatenate([green, dead, clover, gdm, total], axis=-1)\n",
        "\n",
        "def apply_2nd_place_postprocess(preds_5, states=None):\n",
        "    \"\"\"\n",
        "    Physical Ground-Truth Post-Processing:\n",
        "    1. WA Dead Zeroing: Ground truth in Western Australia is strictly 0.0g dead biomass.\n",
        "    2. Range Clipping:\n",
        "       - Clover in [0, 71.7865], Dead in [0, 83.8407], Green in [0, 157.9836]\n",
        "    3. Recompute Physical Identities (GDM = Green + Clover, Total = Green + Dead + Clover).\n",
        "    \"\"\"\n",
        "    preds = np.maximum(np.asarray(preds_5, dtype=np.float32).copy(), 0.0)\n",
        "    if preds.ndim == 1:\n",
        "        preds = preds.reshape(1, -1)\n",
        "    green = preds[:, 0].copy()\n",
        "    dead = preds[:, 1].copy()\n",
        "    clover = preds[:, 2].copy()\n",
        "    \n",
        "    if states is not None:\n",
        "        for idx, st in enumerate(states):\n",
        "            st_str = str(st).strip()\n",
        "            if st_str == 'WA':\n",
        "                dead[idx] = 0.0\n",
        "                \n",
        "    clover = np.clip(clover, 0.0, 71.7865)\n",
        "    dead = np.clip(dead, 0.0, 83.8407)\n",
        "    green = np.clip(green, 0.0, 157.9836)\n",
        "    \n",
        "    gdm = green + clover\n",
        "    total = green + dead + clover\n",
        "    return np.column_stack([green, dead, clover, gdm, total])\n",
        "\n",
        "def soft_physics_postprocess(preds_np, states=None):\n",
        "    return apply_2nd_place_postprocess(preds_np, states=states)\n"
    ]

    # Cell 6: Multi-Backbone Super-Ensemble Inference with TTA
    nb['cells'][6]['source'] = [
        "# 6. Multi-Backbone Super-Ensemble Inference with TTA\n",
        "assert len(CHECKPOINTS) > 0, 'ERROR: No checkpoints found! Please attach your trained models dataset to the notebook.'\n",
        "\n",
        "# 1. Read Test Data\n",
        "test_df_raw = pd.read_csv(CFG.TEST_CSV)\n",
        "if 'target_name' in test_df_raw.columns:\n",
        "    test_df_raw['clean_id'] = test_df_raw['sample_id'].astype(str).apply(lambda x: x.split('__')[0])\n",
        "    unique_test = test_df_raw[['clean_id', 'image_path']].drop_duplicates(subset=['clean_id']).reset_index(drop=True)\n",
        "else:\n",
        "    unique_test = test_df_raw.copy()\n",
        "    if 'clean_id' not in unique_test.columns:\n",
        "        unique_test['clean_id'] = unique_test['sample_id']\n",
        "\n",
        "print(f'Test set: {len(unique_test)} unique pasture images to predict.')\n",
        "\n",
        "# 2. Create DataLoader\n",
        "test_dataset = DualStreamTestDataset(unique_test, CFG.TEST_IMG_DIR, CFG.IMG_SIZE)\n",
        "test_loader = DataLoader(test_dataset, batch_size=CFG.BATCH_SIZE, shuffle=False, num_workers=0)\n",
        "\n",
        "# 3. Predict across all discovered model checkpoints, grouped by architecture\n",
        "vit_predictions = []\n",
        "convnext_predictions = []\n",
        "all_model_info = []\n",
        "\n",
        "for cp_idx, cp_path in enumerate(CHECKPOINTS):\n",
        "    cp_name = os.path.basename(cp_path)\n",
        "    raw_state = torch.load(cp_path, map_location=DEVICE, weights_only=True)\n",
        "    backbone_name, num_targets, clean_sd = detect_model_architecture(raw_state)\n",
        "    \n",
        "    family = 'ConvNeXt' if 'convnext' in backbone_name else 'DINO ViT'\n",
        "    print(f'\\n[{cp_idx + 1}/{len(CHECKPOINTS)}] Evaluating: {cp_name} | Family: {family} ({backbone_name}, targets={num_targets})...')\n",
        "    all_model_info.append({'path': cp_path, 'name': cp_name, 'backbone': backbone_name, 'family': family, 'num_targets': num_targets})\n",
        "    \n",
        "    model = DualStreamBiomassModel(backbone_name=backbone_name, num_targets=num_targets, pretrained=False).to(DEVICE)\n",
        "    model.load_state_dict(clean_sd, strict=False)\n",
        "    model.eval()\n",
        "    \n",
        "    fold_preds = []\n",
        "    with torch.no_grad():\n",
        "        for batch in tqdm(test_loader, desc=f'Inference {cp_name}', leave=False):\n",
        "            img_l = batch['image_left'].to(DEVICE)\n",
        "            img_r = batch['image_right'].to(DEVICE)\n",
        "            \n",
        "            if CFG.USE_TTA:\n",
        "                # Standard view\n",
        "                r_std = model(img_l, img_r)\n",
        "                # Mirrored horizontal view (flip right as left, flip left as right)\n",
        "                r_flip = model(torch.flip(img_r, [3]), torch.flip(img_l, [3]))\n",
        "                avg_r = [(a + b) * 0.5 for a, b in zip(r_std, r_flip)]\n",
        "            else:\n",
        "                avg_r = model(img_l, img_r)\n",
        "                \n",
        "            pred_batch = torch.cat(avg_r, dim=1).cpu().numpy()\n",
        "            fold_preds.append(pred_batch)\n",
        "            \n",
        "    fold_preds_arr = np.concatenate(fold_preds, axis=0)\n",
        "    # Ensure all predictions are 5 targets [Green, Dead, Clover, GDM, Total]\n",
        "    if num_targets == 3:\n",
        "        fold_preds_arr = derive_5_targets(fold_preds_arr)\n",
        "        \n",
        "    if family == 'ConvNeXt':\n",
        "        convnext_predictions.append(fold_preds_arr)\n",
        "    else:\n",
        "        vit_predictions.append(fold_preds_arr)\n",
        "\n",
        "# 4. Multi-Backbone Blended Ensembling\n",
        "print(f'\\n======================================================')\n",
        "print(f'Ensemble Summary:')\n",
        "print(f'  - DINO ViT Models:     {len(vit_predictions)}')\n",
        "print(f'  - ConvNeXt-V2 Models:  {len(convnext_predictions)}')\n",
        "print(f'======================================================')\n",
        "\n",
        "if len(vit_predictions) > 0 and len(convnext_predictions) > 0:\n",
        "    vit_raw = np.mean(vit_predictions, axis=0)\n",
        "    convnext_raw = np.mean(convnext_predictions, axis=0)\n",
        "    \n",
        "    # Normalize blend weights\n",
        "    w_total = CFG.WEIGHT_VIT + CFG.WEIGHT_CONVNEXT\n",
        "    w_v = CFG.WEIGHT_VIT / w_total\n",
        "    w_c = CFG.WEIGHT_CONVNEXT / w_total\n",
        "    \n",
        "    ensemble_raw = w_v * vit_raw + w_c * convnext_raw\n",
        "    print(f'✓ Multi-Backbone Blend Applied: {w_v:.0%} ViT + {w_c:.0%} ConvNeXt-V2')\n",
        "elif len(vit_predictions) > 0:\n",
        "    ensemble_raw = np.mean(vit_predictions, axis=0)\n",
        "    print(f'✓ ViT-Only Ensemble Applied ({len(vit_predictions)} models)')\n",
        "else:\n",
        "    ensemble_raw = np.mean(convnext_predictions, axis=0)\n",
        "    print(f'✓ ConvNeXt-Only Ensemble Applied ({len(convnext_predictions)} models)')\n",
        "\n",
        "states = unique_test['State'].values if 'State' in unique_test.columns else None\n",
        "ensemble_post = apply_2nd_place_postprocess(ensemble_raw, states=states)\n"
    ]

    # Cell 7: Generate, Verify & Export Submissions
    nb['cells'][7]['source'] = [
        "# 7. Generate, Verify & Export Submissions\n",
        "clean_ids = unique_test['clean_id'].tolist()\n",
        "\n",
        "def make_submission(preds_post, filename):\n",
        "    pred_dict = {\n",
        "        clean_ids[i]: {col: float(preds_post[i, c_idx]) for c_idx, col in enumerate(CFG.TARGET_ORDER)}\n",
        "        for i in range(len(clean_ids))\n",
        "    }\n",
        "    \n",
        "    if 'target_name' in test_df_raw.columns:\n",
        "        sub_df = test_df_raw.copy()\n",
        "        sub_df['target'] = sub_df.apply(\n",
        "            lambda row: pred_dict.get(row['clean_id'], {}).get(row['target_name'], 0.0), axis=1\n",
        "        )\n",
        "        res = sub_df[['sample_id', 'target']].copy()\n",
        "    elif os.path.exists(CFG.SAMPLE_SUB_CSV):\n",
        "        sub_t = pd.read_csv(CFG.SAMPLE_SUB_CSV)\n",
        "        sub_t['clean_id'] = sub_t['sample_id'].astype(str).apply(lambda x: x.split('__')[0])\n",
        "        sub_t['target_name'] = sub_t['sample_id'].astype(str).apply(lambda x: x.split('__')[1])\n",
        "        sub_t['target'] = sub_t.apply(\n",
        "            lambda row: pred_dict.get(row['clean_id'], {}).get(row['target_name'], 0.0), axis=1\n",
        "        )\n",
        "        res = sub_t[['sample_id', 'target']].copy()\n",
        "    else:\n",
        "        records = []\n",
        "        for cid in clean_ids:\n",
        "            for col in CFG.TARGET_ORDER:\n",
        "                records.append({'sample_id': f'{cid}__{col}', 'target': pred_dict[cid][col]})\n",
        "        res = pd.DataFrame(records)\n",
        "        \n",
        "    assert res['target'].isna().sum() == 0, f'ERROR: {filename} contains NaN values!'\n",
        "    assert len(res) > 0, f'ERROR: {filename} is empty!'\n",
        "    res.to_csv(filename, index=False)\n",
        "    return res\n",
        "\n",
        "# Primary blended submission (evaluated by Kaggle)\n",
        "final_sub = make_submission(ensemble_post, 'submission.csv')\n",
        "\n",
        "# Individual family auxiliary submissions if both available\n",
        "states = unique_test['State'].values if 'State' in unique_test.columns else None\n",
        "if len(vit_predictions) > 0 and len(convnext_predictions) > 0:\n",
        "    make_submission(apply_2nd_place_postprocess(np.mean(vit_predictions, axis=0), states=states), 'submission_vit.csv')\n",
        "    make_submission(apply_2nd_place_postprocess(np.mean(convnext_predictions, axis=0), states=states), 'submission_convnextv2.csv')\n",
        "    print('Saved auxiliary submissions: submission_vit.csv and submission_convnextv2.csv')\n",
        "\n",
        "print('=' * 50)\n",
        "print(f'SUCCESS! Primary submission saved to: submission.csv')\n",
        "print(f'Total predictions: {len(final_sub)}')\n",
        "print('=' * 50)\n",
        "print('\\nTarget Distribution:')\n",
        "print(final_sub['target'].describe())\n",
        "print('\\nFirst 10 Rows:')\n",
        "print(final_sub.head(10))\n"
    ]

    with open(nb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
    print("Successfully updated src/notebooks/inference.ipynb!")

if __name__ == '__main__':
    update_training_notebook()
    update_inference_notebook()
